"""Add user_id to DDNSConfig

Revision ID: 93cd3262a5a4
Revises: 
Create Date: 2024-09-12 14:41:07.877308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93cd3262a5a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddns_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_ddns_config_user_id', 'user', ['user_id'], ['id'])  # Add explicit name for the foreign key
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddns_config', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ddns_config_user_id', type_='foreignkey')  # Drop the foreign key by its name
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
